"""v1_initial_schema

Revision ID: 22cf0ac436cd
Revises: 
Create Date: 2026-04-16 08:52:54.826163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '22cf0ac436cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('display_price', sa.Text(), nullable=False),
    sa.Column('amount_usd_cents', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('dodo_product_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_usd_cents > 0', name='billing_plans_amount_usd_cents_check'),
    sa.CheckConstraint('daily_limit > 0', name='billing_plans_daily_limit_check'),
    sa.CheckConstraint('duration_days > 0', name='billing_plans_duration_days_check'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_feature_flags_updated_at', 'feature_flags', ['updated_at'], unique=False)
    op.create_table('pois',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulated_billing_plans',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_limit > 0', name='simulated_billing_plans_daily_limit_check'),
    sa.CheckConstraint('duration_hours > 0', name='simulated_billing_plans_duration_hours_check'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_simulated_billing_plans_cohort', 'simulated_billing_plans', ['cohort'], unique=False)
    op.create_index('idx_simulated_billing_plans_is_active', 'simulated_billing_plans', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_customer_id', sa.Text(), nullable=True),
    sa.Column('ab_cohort', sa.Text(), server_default=sa.text("'A'"), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('provider_customer_id')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), server_default=sa.text("'login'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_ip_hash', sa.Text(), nullable=True),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='magic_link_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='magic_link_tokens_token_hash_key')
    )
    op.create_index('idx_magic_tokens_email_created', 'magic_link_tokens', ['email', 'created_at'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('provider_intent_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['billing_plans.code'], name='payment_intents_plan_code_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_intents_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_intent_id'),
    sa.UniqueConstraint('provider_intent_id', name='payment_intents_provider_intent_id_key')
    )
    op.create_index('idx_payment_intents_provider_intent_id', 'payment_intents', ['provider_intent_id'], unique=True)
    op.create_index('idx_payment_intents_user_created_at', 'payment_intents', ['user_id', 'created_at'], unique=False)
    op.create_table('simulated_payment_intents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'initiated'"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'simulated_paid'"), nullable=False),
    sa.Column('upgraded_from_anon_id', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('requester_ip_hash', sa.Text(), nullable=True),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source = 'simulated_paid'", name='simulated_payment_intents_source_check'),
    sa.CheckConstraint("status IN ('initiated', 'magic_sent', 'activated', 'expired', 'revoked')", name='simulated_payment_intents_status_check'),
    sa.ForeignKeyConstraint(['plan_code'], ['simulated_billing_plans.code'], name='simulated_payment_intents_plan_code_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='simulated_payment_intents_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulated_payment_intents_plan_code', 'simulated_payment_intents', ['plan_code'], unique=False)
    op.create_index('idx_simulated_payment_intents_status_created', 'simulated_payment_intents', ['status', 'created_at'], unique=False)
    op.create_index('idx_simulated_payment_intents_user_created', 'simulated_payment_intents', ['user_id', 'created_at'], unique=False)
    op.create_table('ugc_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_anon_id', sa.Text(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('reporter_tier', sa.Text(), server_default=sa.text("'free'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('noise_type', sa.Text(), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('moderator_note', sa.Text(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('geo_cell', sa.Text(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('nearest_poi_id', sa.Integer(), nullable=True),
    sa.Column('nearest_poi_distance_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('char_length(category) <= 50', name='ugc_reports_category_check'),
    sa.CheckConstraint('char_length(noise_type) <= 50', name='ugc_reports_noise_type_check'),
    sa.CheckConstraint('severity >= 1 AND severity <= 5', name='ugc_reports_severity_check'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['ugc_reports.id'], name='ugc_reports_duplicate_of_id_fkey'),
    sa.ForeignKeyConstraint(['nearest_poi_id'], ['pois.id'], name='ugc_reports_nearest_poi_id_fkey'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ugc_reports_content_hash', 'ugc_reports', ['content_hash'], unique=False)
    op.create_index('ugc_reports_geo_cell_created_at', 'ugc_reports', ['geo_cell', 'created_at'], unique=False)
    op.create_index('ugc_reports_reporter_anon_created_at', 'ugc_reports', ['reporter_anon_id', 'created_at'], unique=False)
    op.create_index('ugc_reports_reporter_user_created_at', 'ugc_reports', ['reporter_user_id', 'created_at'], unique=False)
    op.create_index('ugc_reports_status_created_at', 'ugc_reports', ['status', 'created_at'], unique=False)
    op.create_index('ugc_reports_status_occurred_at', 'ugc_reports', ['status', 'occurred_at'], unique=False)
    op.create_table('user_location_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anon_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('input_kind', sa.Text(), nullable=False),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('normalized_input', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('demand_cell_id', sa.Text(), nullable=True),
    sa.Column('request_country', sa.Text(), nullable=True),
    sa.Column('request_city', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('result_status', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('is_duplicate_window', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_location_queries_anon_created', 'user_location_queries', ['anon_id', 'created_at'], unique=False)
    op.create_index('idx_user_location_queries_created_at', 'user_location_queries', ['created_at'], unique=False)
    op.create_index('idx_user_location_queries_demand_cell_created', 'user_location_queries', ['demand_cell_id', 'created_at'], unique=False)
    op.create_index('idx_user_location_queries_session_created', 'user_location_queries', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_user_location_queries_user_created', 'user_location_queries', ['user_id', 'created_at'], unique=False)
    op.create_table('user_passes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.Text(), nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['billing_plans.code'], name='user_passes_plan_code_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_passes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id'),
    sa.UniqueConstraint('provider_payment_id', name='user_passes_provider_payment_id_key')
    )
    op.create_index('idx_user_passes_user_id', 'user_passes', ['user_id'], unique=False)
    op.create_table('simulated_user_passes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.Text(), nullable=False),
    sa.Column('simulated_intent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','expired','revoked')", name='simulated_user_passes_status_check'),
    sa.ForeignKeyConstraint(['plan_code'], ['simulated_billing_plans.code'], name='simulated_user_passes_plan_code_fkey'),
    sa.ForeignKeyConstraint(['simulated_intent_id'], ['simulated_payment_intents.id'], name='simulated_user_passes_simulated_intent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='simulated_user_passes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulated_user_passes_intent', 'simulated_user_passes', ['simulated_intent_id'], unique=False)
    op.create_index('idx_simulated_user_passes_status_expires', 'simulated_user_passes', ['status', 'expires_at'], unique=False)
    op.create_index('idx_simulated_user_passes_user_expires', 'simulated_user_passes', ['user_id', 'expires_at'], unique=False)
    op.create_table('ugc_report_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(url) <= 2000', name='ugc_report_evidence_url_check'),
    sa.ForeignKeyConstraint(['report_id'], ['ugc_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'url_hash', name='ugc_report_evidence_unique_per_report')
    )
    op.create_index('ugc_report_evidence_report_id', 'ugc_report_evidence', ['report_id'], unique=False)
    op.create_table('funnel_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_source', sa.Text(), nullable=False),
    sa.Column('event_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('anon_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('effective_tier', sa.Text(), nullable=False),
    sa.Column('target_tier', sa.Text(), nullable=True),
    sa.Column('transition_name', sa.Text(), nullable=True),
    sa.Column('related_query_id', sa.Integer(), nullable=True),
    sa.Column('related_simulated_intent_id', sa.UUID(), nullable=True),
    sa.Column('related_simulated_pass_id', sa.UUID(), nullable=True),
    sa.Column('related_payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('related_user_pass_id', sa.UUID(), nullable=True),
    sa.Column('ui_surface', sa.Text(), nullable=True),
    sa.Column('check_type', sa.Text(), nullable=True),
    sa.Column('cohort', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("NOT (event_name = 'check_completed' AND check_type = 'demand' AND effective_tier NOT IN ('simulated_paid', 'paid_1_day', 'paid_3_days'))", name='funnel_events_demand_completion_tier_check'),
    sa.CheckConstraint("check_type IS NULL OR check_type IN ('construction', 'demand')", name='funnel_events_check_type_check'),
    sa.CheckConstraint("effective_tier IN ('free', 'simulated_paid', 'paid_1_day', 'paid_3_days')", name='funnel_events_effective_tier_check'),
    sa.CheckConstraint("event_name <> 'check_completed' OR related_query_id IS NOT NULL", name='funnel_events_check_completed_requires_query'),
    sa.CheckConstraint("target_tier IS NULL OR target_tier IN ('simulated_paid', 'paid_1_day', 'paid_3_days')", name='funnel_events_target_tier_check'),
    sa.CheckConstraint("transition_name IS NULL OR transition_name IN ('free_to_simulated_paid', 'free_to_paid_1_day', 'free_to_paid_3_days')", name='funnel_events_transition_name_check'),
    sa.CheckConstraint("ui_surface IS NULL OR ui_surface IN ('construction_level_page', 'demand_level_page', 'hero_unlock_button', 'user_access_modal', 'share_modal', 'about_modal')", name='funnel_events_ui_surface_check'),
    sa.CheckConstraint('event_version > 0', name='funnel_events_event_version_check'),
    sa.ForeignKeyConstraint(['related_payment_intent_id'], ['payment_intents.id'], name='funnel_events_related_payment_intent_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_query_id'], ['user_location_queries.id'], name='funnel_events_related_query_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_simulated_intent_id'], ['simulated_payment_intents.id'], name='funnel_events_related_simulated_intent_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_simulated_pass_id'], ['simulated_user_passes.id'], name='funnel_events_related_simulated_pass_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_pass_id'], ['user_passes.id'], name='funnel_events_related_user_pass_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='funnel_events_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funnel_events_anon_created', 'funnel_events', ['anon_id', 'created_at'], unique=False)
    op.create_index('idx_funnel_events_created_at', 'funnel_events', ['created_at'], unique=False)
    op.create_index('idx_funnel_events_event_created', 'funnel_events', ['event_name', 'created_at'], unique=False)
    op.create_index('idx_funnel_events_session_created', 'funnel_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_funnel_events_user_created', 'funnel_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_funnel_events_user_created', table_name='funnel_events')
    op.drop_index('idx_funnel_events_session_created', table_name='funnel_events')
    op.drop_index('idx_funnel_events_event_created', table_name='funnel_events')
    op.drop_index('idx_funnel_events_created_at', table_name='funnel_events')
    op.drop_index('idx_funnel_events_anon_created', table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_index('ugc_report_evidence_report_id', table_name='ugc_report_evidence')
    op.drop_table('ugc_report_evidence')
    op.drop_index('idx_simulated_user_passes_user_expires', table_name='simulated_user_passes')
    op.drop_index('idx_simulated_user_passes_status_expires', table_name='simulated_user_passes')
    op.drop_index('idx_simulated_user_passes_intent', table_name='simulated_user_passes')
    op.drop_table('simulated_user_passes')
    op.drop_index('idx_user_passes_user_id', table_name='user_passes')
    op.drop_table('user_passes')
    op.drop_index('idx_user_location_queries_user_created', table_name='user_location_queries')
    op.drop_index('idx_user_location_queries_session_created', table_name='user_location_queries')
    op.drop_index('idx_user_location_queries_location', table_name='user_location_queries', postgresql_using='gist')
    op.drop_index('idx_user_location_queries_demand_cell_created', table_name='user_location_queries')
    op.drop_index('idx_user_location_queries_created_at', table_name='user_location_queries')
    op.drop_index('idx_user_location_queries_anon_created', table_name='user_location_queries')
    op.drop_table('user_location_queries')
    op.drop_index('ugc_reports_status_occurred_at', table_name='ugc_reports')
    op.drop_index('ugc_reports_status_created_at', table_name='ugc_reports')
    op.drop_index('ugc_reports_reporter_user_created_at', table_name='ugc_reports')
    op.drop_index('ugc_reports_reporter_anon_created_at', table_name='ugc_reports')
    op.drop_index('ugc_reports_geom_gist', table_name='ugc_reports', postgresql_using='gist')
    op.drop_index('ugc_reports_geo_cell_created_at', table_name='ugc_reports')
    op.drop_index('ugc_reports_content_hash', table_name='ugc_reports')
    op.drop_index('idx_ugc_reports_geom', table_name='ugc_reports', postgresql_using='gist')
    op.drop_table('ugc_reports')
    op.drop_index('idx_simulated_payment_intents_user_created', table_name='simulated_payment_intents')
    op.drop_index('idx_simulated_payment_intents_status_created', table_name='simulated_payment_intents')
    op.drop_index('idx_simulated_payment_intents_plan_code', table_name='simulated_payment_intents')
    op.drop_table('simulated_payment_intents')
    op.drop_index('idx_payment_intents_user_created_at', table_name='payment_intents')
    op.drop_index('idx_payment_intents_provider_intent_id', table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index('idx_magic_tokens_email_created', table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_table('users')
    op.drop_index('idx_simulated_billing_plans_is_active', table_name='simulated_billing_plans')
    op.drop_index('idx_simulated_billing_plans_cohort', table_name='simulated_billing_plans')
    op.drop_table('simulated_billing_plans')
    op.drop_index('idx_pois_geom', table_name='pois', postgresql_using='gist')
    op.drop_table('pois')
    op.drop_index('idx_feature_flags_updated_at', table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
