"""add_retention_indexes

Revision ID: bf88275af98e
Revises: 22cf0ac436cd
Create Date: 2026-04-17 13:16:20.564531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf88275af98e'
down_revision: Union[str, Sequence[str], None] = '22cf0ac436cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_magic_tokens_expires_at', 'magic_link_tokens', ['expires_at'], unique=False)
    op.create_index('idx_magic_tokens_redeemed_at', 'magic_link_tokens', ['redeemed_at'], unique=False)
    op.create_index('idx_simulated_payment_intents_created_at', 'simulated_payment_intents', ['created_at'], unique=False)
    op.create_index('idx_simulated_user_passes_updated_at', 'simulated_user_passes', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_simulated_user_passes_updated_at', table_name='simulated_user_passes')
    op.drop_index('idx_simulated_payment_intents_created_at', table_name='simulated_payment_intents')
    op.drop_index('idx_magic_tokens_redeemed_at', table_name='magic_link_tokens')
    op.drop_index('idx_magic_tokens_expires_at', table_name='magic_link_tokens')
    # ### end Alembic commands ###
